### ISSUE TITLE
Allow One to Gonfigure Global List of Acronyms  

### ISSUE THREAD

**Issue by sshaw** [piotrmurach/strings-case#3]
```rb
Strings::Core.configure do |config|
  config.acronym "NYC"
end
```

Having to pass these around everywhere can be a pain. And when coming from `ActiveSupport::Inflector`, can also make the transition easier.

**Comment by piotrmurach** [comment]
Agree 💯 Initially, I wanted this module to be really functional without any state. But I can appreciate that's not necessarily how Ruby is expected to work. In the `strings-numeral` gem I decided to go with the configuration via initialize block [see](https://github.com/piotrmurach/strings-numeral#26-configuration).

```ruby
casing = Strings::Case.new do |config|
  config.acronyms
end
casing.camelcase(...)
```

**Comment by piotrmurach** [comment]
Added the ability to [configure](https://github.com/piotrmurach/strings-case#21-configure) acronyms once on an instance:

```ruby
strings = Strings::Case.new
strings.configure do |config|
  config.acronym "HTTP"
  config.acronym "XML"

  # or config.acronym "HTTP", "XML"
end
```
