### ISSUE TITLE
#camelcase with leading underscores

### ISSUE THREAD

**Issue by mkdynamic** [piotrmurach/strings-case#5]
The current behavior of `camelcase` eats any leading underscores:

```ruby
irb(main):008:0> Strings::Case.snakecase("_foo")
=> "_foo"
irb(main):009:0> Strings::Case.camelcase("_foo")
=> "foo"
```

This makes it lossy when going from `_foo_bar` to `fooBar` and back to `foo_bar`. Leading underscores are rare, but I think it is a convention used to signify private variables in both camelCase and snake_case (for example in JS, it is not uncommon to see `_foo` variables or keys in Objects etc.).

I see this case defined explicitly in the specs, so the current behavior seems deliberate. Thoughts on changing the behavior to leave leading underscores alone?

**Comment by piotrmurach** [comment]
Hi Mark 👋 

Thanks for trying out this gem. 

This behaviour is consistent with `ActiveSupport::Inflector` which is one of the goals to help people migrate over.

```ruby
ActiveSupport::Inflector.camelize("_foo") # => "Foo"
```

Internally the `_` character is considered one of the delimiters. It would complicate the implementation significantly if we decided to have this rule of preserving the leading underscores. This could possibly work with a flag but similarly, reduce performance for everyone else who doesn't need this functionality. Therefore I'm reluctant about adding this.

Do you have a code snippet of what you're trying to achieve? I'd be happy to review PR as well.

**Comment by mkdynamic** [comment]
@piotrmurach Howdy! Thanks for the response.

I have a pretty specific use case, where I am building a library (for Rails/React integration) that needs deep transformation of Hash keys to and from camelCase and snake_case. And specifically in a way that is round-tripable/reversible. Ideally also fast too, since it runs for fairly large Hashes for every request/response.

I noticed that ActiveSupport::Inflector doesn’t work for this due to the way it handles leading underscores. Hence my motivation for investigating alternatives.

Changing the default doesn’t make sense. But a configuration option would be fantastic. This might be very specific to my use case and esoteric, so totally understand if it’s out of scope. My plan C will be to implement the transformation myself :)

Need to think more deeply on whether the reversibility property is actually possible… do you have any hunches based on your experience writing this library?

**Comment by piotrmurach** [comment]
That's an interesting problem you have there. Thanks for sharing. Crafting a custom solution would probably be the way forward. Though I'm not sure whether this is actually possible. May be wrong here. A quick example that sprang to my mind is trying to convert a `__foo-_-bar` key into a camelcase preserving leading underscores that would yield `__foo--Bar`. This assumes that the only delimiter is `_`. But how would you know when reverting back to snake case where to insert the `_`? You've lost this information. It seems that without certain rules for hash keys, it would be difficult to achieve your goal unless I'm missing something here.

Having said that I still think you could preserve prefixes in this gem(minus the reversibility requirement). I'd try first adjusting this gem parser. For example, allow to override the delimiters to only specify let's say `_`. Then add a flag that preserves prefix and suffix characters when an underscore is found.

Anyhow, as I mentioned previously. This is something I won't be working on and if you feel strongly about this feature and manage to come up with some neat solution please let me know. I'd be curious what you've done in the end. But for now, I'm going to close this issue.
